name: 'Thank You Action'
description: 'Say "Thank You" to new pull requests'
author: 'Ted'

inputs:
  GITHUB_TOKEN:
    description: 'Github token'
    required: true
  TENOR_TOKEN:
    description: 'Tenor API token'
    required: true  
  message:
    description: 'Message that gets sent to new pull requests'
    default: 'Thank you for submitting a pull request! We will try to review this as soon as we can.'   
    

runs:
  using: 'node12'
  main: 'dist/index.js'      
